#!/bin/bash

##############################################################################
#                            Include functions                               #
##############################################################################

  source ../../global.conf                              # Include Global Conf
  source ${install_path}/scripts/includes/functions.sh  # Include Functions

##############################################################################
#                          Setup NFS Shares                                  #
##############################################################################

start_spinner "Configuring nfs shares"

if [ ! -d "${images_path}" ]; then
  if [ "${debugging}" = "yes" ]; then
    echo "DEBUG: Images directory doesnt exist (${images_path}), creating"
  fi
mkdir ${images_path}
fi

# Remove Lines
sed -i "/#generated by anydeploy/d" /etc/exports

# Add Lines
echo "# Don't remove #generated by anydeploy comments as it's used by scripts to modify this file" >> /etc/exports
echo "${install_path} *(rw,no_root_squash,async,insecure,no_subtree_check) #generated by anydeploy" >> /etc/exports
echo "${images_path} *(rw,no_root_squash,async,insecure,no_subtree_check) #generated by anydeploy" >> /etc/exports
echo "${anynet_amd64} *(rw,no_root_squash,async,insecure,no_subtree_check) #generated by anydeploy" >> /etc/exports
sleep 1
stop_spinner $?

start_spinner "Restarting NFS"
service nfs-kernel-server restart
sleep 1
stop_spinner $?
